import './About.css';

interface AboutProps {
    onClose: () => void;
}

function About({ onClose }: AboutProps) {
    return (
        <div className="about-overlay" onClick={onClose}>
            <div className="about-modal" onClick={(e) => e.stopPropagation()}>
                <button className="close-button" onClick={onClose}>✕</button>
                
                <div className="about-content">
                    <h1>🌱 Inside Journal</h1>
                    <p className="version">Version 1.0.0</p>
                    
                    <div className="about-section">
                        <h2>About</h2>
                        <p>
                            Inside Journal is your personal mental wellness companion, powered by cutting-edge AI technology. 
                            We believe that understanding your emotions is the first step toward better mental health. 
                            Our platform uses advanced sentiment analysis and natural language processing to help you 
                            gain deeper insights into your thoughts and emotional patterns.
                        </p>
                        <p>
                            Every journal entry you create is analyzed to identify sentiment, extract key themes, 
                            and provide personalized affirmations that support your mental wellness journey. 
                            Track your progress over time with intuitive trend visualizations and discover patterns 
                            in your emotional well-being.
                        </p>
                    </div>

                    <div className="about-section">
                        <h2>Features</h2>
                        <ul className="features-list">
                            <li>AI-powered sentiment analysis that understands the emotional tone of your entries</li>
                            <li>Automatic key phrase extraction to identify important themes in your thoughts</li>
                            <li>Personalized affirmations and insightful summaries generated by GPT-4</li>
                            <li>Secure cloud storage ensuring your journal entries are always safe and accessible</li>
                            <li>Voice-to-text journaling for convenient hands-free entry creation</li>
                            <li>Trend analysis visualizations to track your emotional patterns over time</li>
                            <li>Real-time insights with comprehensive application monitoring</li>
                            <li>Privacy-focused design with enterprise-grade security</li>
                        </ul>
                    </div>

                    <div className="about-section">
                        <h2>Technology Stack</h2>
                        <div className="tech-stack">
                            <span className="tech-badge">Azure OpenAI GPT-4</span>
                            <span className="tech-badge">Azure Cognitive Services</span>
                            <span className="tech-badge">Azure Cosmos DB</span>
                            <span className="tech-badge">Azure Blob Storage</span>
                            <span className="tech-badge">Application Insights</span>
                            <span className="tech-badge">React 19</span>
                            <span className="tech-badge">.NET 8</span>
                            <span className="tech-badge">TypeScript</span>
                        </div>
                    </div>

                    <div className="about-section">
                        <h2>Privacy & Security</h2>
                        <p>
                            Your privacy is our top priority. All journal entries are encrypted and stored securely 
                            in Azure Cosmos DB. We use managed identity authentication to ensure secure communication 
                            between services, and your data is never shared with third parties. Application Insights 
                            telemetry is anonymized and used solely to improve the user experience.
                        </p>
                    </div>

                    <div className="about-section">
                        <h2>Getting Started</h2>
                        <p>
                            Simply write your thoughts in the journal entry box and click "Save & Analyze Entry". 
                            Our AI will process your entry, identify the sentiment, extract key phrases, and provide 
                            you with a personalized summary and affirmation. Over time, you'll be able to see trends 
                            in your emotional well-being and gain valuable insights into your mental health journey.
                        </p>
                    </div>

                    <div className="about-section">
                        <p className="contact-info">
                            Built with ❤️ using Azure AI Services | © 2025 Inside Journal
                        </p>
                    </div>
                </div>
            </div>
        </div>
    );
}

export default About;
